// <auto-generated />
using System;
using BarClip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarClip.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BarClip.Data.Schema.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Lift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LifterFilter")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginalVideoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProcessedVideoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Successful")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("OriginalVideoId")
                        .IsUnique();

                    b.HasIndex("ProcessedVideoId");

                    b.HasIndex("SessionId");

                    b.ToTable("Lifts");
                });

            modelBuilder.Entity("BarClip.Data.Schema.OriginalVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentProcessedVideoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TrimFinish")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TrimStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("OriginalVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.ProcessedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalVideoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalVideoId");

                    b.HasIndex("UserId");

                    b.ToTable("ProcessedVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int?>("RepsMade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepsMissed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BarClip.Data.Schema.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Lift", b =>
                {
                    b.HasOne("BarClip.Data.Schema.Exercise", "Exercise")
                        .WithMany("Lifts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarClip.Data.Schema.OriginalVideo", "OriginalVideo")
                        .WithOne("Lift")
                        .HasForeignKey("BarClip.Data.Schema.Lift", "OriginalVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarClip.Data.Schema.ProcessedVideo", "ProcessedVideo")
                        .WithMany()
                        .HasForeignKey("ProcessedVideoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarClip.Data.Schema.Session", "Session")
                        .WithMany("Lifts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("OriginalVideo");

                    b.Navigation("ProcessedVideo");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BarClip.Data.Schema.OriginalVideo", b =>
                {
                    b.HasOne("BarClip.Data.Schema.Session", "Session")
                        .WithMany("OriginalVideos")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarClip.Data.Schema.User", "User")
                        .WithMany("OriginalVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarClip.Data.Schema.ProcessedVideo", b =>
                {
                    b.HasOne("BarClip.Data.Schema.OriginalVideo", "OriginalVideo")
                        .WithMany("ProcessedVideos")
                        .HasForeignKey("OriginalVideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarClip.Data.Schema.User", "User")
                        .WithMany("TrimmedVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Session", b =>
                {
                    b.HasOne("BarClip.Data.Schema.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Exercise", b =>
                {
                    b.Navigation("Lifts");
                });

            modelBuilder.Entity("BarClip.Data.Schema.OriginalVideo", b =>
                {
                    b.Navigation("Lift");

                    b.Navigation("ProcessedVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Session", b =>
                {
                    b.Navigation("Lifts");

                    b.Navigation("OriginalVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.User", b =>
                {
                    b.Navigation("OriginalVideos");

                    b.Navigation("Sessions");

                    b.Navigation("TrimmedVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
